### ISSUE TITLE
train/test with own dataset

### ISSUE THREAD

**Issue by Jing-lun** [azad96/cosypose-custom#1]
Hi @azad96,
I appreciate your single-view inference script, it simplifies the source code a lot and helps me test the cosypose in a live demo way!

Anyhow, I would like to train from the scratch with my own dataset, which means I need to run: python -m cosypose.scripts.run_detector_training --config bop-MY_DATASET-pbr at first.

However, by doing so, I also need to provide a 'test_targets_bop19.json' file according to the cosypose source code,
do you have any ideas for this part? Can I train my own dataset without providing a json file?

Thank you!

**Comment by azad96** [comment]
Hi @Jing-lun,

First of all, thank you for taking an interest in this repo. You need to create that json file for your test dataset. I've just added data_scripts/generate_target_json.py that you can use to create it. I also need a picke file for bounding box informations when I start a training. If you need that as well, I've also added data_scripts/generate_bbox_for_test.py. You need to put the json file inside local_data/bop_datasets/DATASET_NAME/ and the pickle file inside local_data/saved_detections/

**Comment by Jing-lun** [comment]
> Hi @Jing-lun,
> 
> First of all, thank you for taking an interest in this repo. You need to create that json file for your test dataset. I've just added data_scripts/generate_target_json.py that you can use to create it. I also need a picke file for bounding box informations when I start a training. If you need that as well, I've also added data_scripts/generate_bbox_for_test.py. You need to put the json file inside local_data/bop_datasets/DATASET_NAME/ and the pickle file inside local_data/saved_detections/

Hi @azad96, you're amazing! This is what I want to check! Actually, I noticed that we need to provide both json and pickle file for training purposes, I believe with your resources it would save me a lot of time to do it!

**Comment by azad96** [comment]
I'll close this issue then. If you need further assistance, you can reopen this issue or open a new one. Good luck :)

**Comment by Jing-lun** [comment]
> Hi @Jing-lun,
> 
> First of all, thank you for taking an interest in this repo. You need to create that json file for your test dataset. I've just added data_scripts/generate_target_json.py that you can use to create it. I also need a picke file for bounding box informations when I start a training. If you need that as well, I've also added data_scripts/generate_bbox_for_test.py. You need to put the json file inside local_data/bop_datasets/DATASET_NAME/ and the pickle file inside local_data/saved_detections/



> I'll close this issue then. If you need further assistance, you can reopen this issue or open a new one. Good luck :)

Hi @azad96, first of all, thanks for the provided scripts, I used them generate the json and pkl file for my own dataset, and put them into the correct path.
However, when I ran "cosypose.scripts.run_detector_training --config bop-MY_DATASET-pbr", I still got an error on evaluation part (results = run_detection_eval(cfg, detector=detector)), it returned me a ZeroDivisionError: division by zero. It is because my "n_gt_valid" in file "detecion_meters.py" line 191 got a 0. So I think it may be caused by the loaded pkl file?
Did you have this issue when you trained your own dataset from scratch? Appreciate it!

**Comment by azad96** [comment]
hi @Jing-lun, I only trained the pose network (coarse and refiner), so I don't know if detector training is different than this. However, this error seems like it is related to something else. I'd first load the pickle file and have a look at its inside. Then, I'd go to the line where it throws that error and backtrace from that point. If you get some new information about this, please let me know.

**Comment by Jing-lun** [comment]
> hi @Jing-lun, I only trained the pose network (coarse and refiner), so I don't know if detector training is different than this. However, this error seems like it is related to something else. I'd first load the pickle file and have a look at its inside. Then, I'd go to the line where it throws that error and backtrace from that point. If you get some new information about this, please let me know.

Azad you're the best! Thanks for your prompt reply. Let me have a try tomorrow since I couldn't access my workstation during the night!
